### ISSUE TITLE
Keep a log of versions when specific data set objects change.

### ISSUE THREAD

**Issue by gfinak** [ropensci/DataPackageR#49]
If a data set in a package changes, currently we only record the md5sum. 
It would be nice to keep a record of the DataVersion and package version numbers where a data set has changed, so rolling back is easier when it's necessary. Currently this would only be recorded in the git log.

**Comment by raphg** [comment]
That’s a great idea.

Sent from my iPhone

On Sep 6, 2018, at 9:32 AM, Greg Finak <notifications@github.com<mailto:notifications@github.com>> wrote:


If a data set in a package changes, currently we only record the md5sum.
It would be nice to keep a record of the DataVersion and package version numbers where a data set has changed, so rolling back is easier when it's necessary. Currently this would only be recorded in the git log.

**Comment by gfinak** [comment]
- NEWS.md file is now automatically updated when data sets change.

![image](https://user-images.githubusercontent.com/1385593/45436363-7f64cf80-b667-11e8-95be-770411fbcc62.png)
