### ISSUE TITLE
The description file of a new data package should have the Depends field populated with packages it requires to compile.

### ISSUE THREAD

**Issue by gfinak** [ropensci/DataPackageR#53]

**Comment by slager** [comment]
I think #116 addressed this.

Building the data package requires loading DataPackageR, which also loads the dependencies needed for building the data package, vignettes, etc.

Installation can be via DataPackageR with the install = TRUE arguments in package_build or document(), or with base R install.packages() with the tarball produced by package_build().  I don't think any additional dependencies are necessary once the package is built and installed.
