### ISSUE TITLE
use_description error building README

### ISSUE THREAD

**Issue by jsta** [ropensci/DataPackageR#59]
I was getting an error building `README.Rmd`: 

> fmt[[1]] : subscript out of bounds

I traced the error back to the fact that `datapackage_skeleton` calls `create_package` without setting the `fields` argument. 

I solved the error by setting the `usethis.description` field in my `.Rprofile` (see https://usethis.r-lib.org/reference/use_description.html).

 Could this process be made more user friendly possibly by prompting the user for input to `fields`?

**Comment by gfinak** [comment]
Can you clarify if you were getting an error building `DataPackageR` or building a package made with `DataPackageR`?

**Comment by jsta** [comment]
Running the following commands:

`$ git clone https://github.com/ropensci/DataPackageR.git`
`$ cd DataPackageR`
`$ Rscript -e "rmarkdown::render('README.Rmd')"`

**Comment by gfinak** [comment]
I get no error during that process.

**Comment by jsta** [comment]
Hmm, maybe this is a `usethis` issue and I have a wrongly formatted `devtools.desc` field in my `.Rprofile`.

**Comment by gfinak** [comment]
Let me know if you can reproduce this and trace it back to `DataPackageR`, happy to help if I can.
