### ISSUE TITLE
Parsing bug when renaming a data object.

### ISSUE THREAD

**Issue by gfinak** [ropensci/DataPackageR#63]
When a  data object is renamed, rebuilding the package gives an error when checking the datadigest.
To reproduce:
1. change the name of a data object in an Rmd and in the yml.
2. build the package.

To fix:
Correct the logic comparing data digests for an object that exists in the data digest file but not elsewhere. Object needs to be removed correctly from the data digest file.

**Comment by slager** [comment]
This got fixed in #95.
