### ISSUE TITLE
NEWS doesn't reflect actual changes to data files.

### ISSUE THREAD

**Issue by gfinak** [ropensci/DataPackageR#67]
Expected behavior: When rebuilding a package and a data set changes, the NEWS file is updated to reflect only the changing data set.

Observed behavior: Sometimes the news file indicates that multiple data sets have changed even when only one has changed, despite no changes in the DATADIGEST string.
 
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by slager** [comment]
reprex?
