### ISSUE TITLE
Getting your pkgdown site online 

### ISSUE THREAD

**Issue by jeroen** [ropensci/DataPackageR#72]
Hi! We have started build documentation for all ropensci packages, see: https://ropensci.org/technotes/2019/06/07/ropensci-docs/

Your site currently fails to build due to a minor issue with the formatting of the NEWS.md file, see https://dev.ropensci.org/job/DataPackageR/lastBuild/console

Could you try to look into this? Let me know if you need any help!

**Comment by gfinak** [comment]
Thanks I'll do that. I'm currently traveling so it may take a minute. I'll definitely reach out if I could use a hand. 
Thanks.

**Comment by slager** [comment]
ropensci pkgdown site appears to have been successfully built well after the dates of this conversation.
