### ISSUE TITLE
Heads up re: changes in usethis

### ISSUE THREAD

**Issue by jennybc** [ropensci/DataPackageR#73]
I just merged a PR from @jimhester in usethis, where we've finally managed to switch user messaging to `message()` instead of `cat()`, because we now have an attractive way to prevent such messages from being displayed in red.

Jim kindly ran revdeps and it shows you may need to tweak your tests. Jim even suggests a patch here:

https://github.com/r-lib/usethis/pull/928#issuecomment-553091603

A usethis release is probably a 4-6 weeks away.

**Comment by gfinak** [comment]
Thanks, @jennybc .
I've pushed the fix, it tests cleanly and is ready to merge when the next usethis release comes out.

**Comment by jennybc** [comment]
Just a ping to say this is still being seen by us and, now, CRAN auto-check. But I think it will not hold up our release, since we have given plenty of advance notice.
