### ISSUE TITLE
Migrate CI from Travis CI and Appveyor to GitHub Actions.

### ISSUE THREAD

**Issue by jmtaylor-fhcrc** [ropensci/DataPackageR#78]
Travis CI is discontinuing its free service. GitHub Actions can provide services provided by Travis CI and Appveyor. This repository needs a CI workflow added via GitHub Actions so that development with CI can continue.

**Comment by mariev** [comment]
mostly addressed via PR #79; 

it looks like DESCRIPTION imposes R >= 3.5.0 - should R 3.4 & 3.3. can be removed from c.i. yml ?

**Comment by mariev** [comment]
@jmtaylor-fhcrc can we close this issue?
