### ISSUE TITLE
Review DataPackageR current documentation for accuracy

### ISSUE THREAD

**Issue by mariev** [ropensci/DataPackageR#82]
Make sure that any references that package points to e.g. README, ropensci are current and do not refer to historical practices.

**Comment by mariev** [comment]
online references:
- https://ropensci.org/blog/2018/09/18/datapackager/
- https://github.com/ropensci/DataPackageR/blob/master/vignettes/usingDataPackageR.md
- https://gatesopenresearch.org/articles/2-31/v2

**Comment by slager** [comment]
fixed by https://github.com/ropensci/DataPackageR/commit/cbae03fa646e72212f92c5d4304f3118a5c2a6ef
