### ISSUE TITLE
Install specific data version

### ISSUE THREAD

**Issue by shirdekel** [ropensci/DataPackageR#91]
I understand that we can test for a particular data version using `assert_data_version()` and I know that I can install a particular reference/tag in a package from Github using, for instance, `devtools::install_github("ropensci/DataPackageR@v0.1.1")`. Is there a recommended way to install a particular data version of a data package from the installation? In other words, what happens after `assert_data_version()` fails? Where/how can the user find the relevant data version?

**Comment by slager** [comment]
Ideally, your data package development would be under version control (e.g., git). In that case, to find an earlier version of your data package, you would do a `git checkout` of an earlier commit or tag to access an earlier version of your data package.
